# Splitting examples into groups
   - To be run in root

In [5]:
import pandas as pd
import numpy as np

# Miguel set of first 36 Rows
df = pd.read_csv('./Dataset/Experimentation/UniqueVerbs.csv')
df = df.loc[0:35]
df

                          Verbs
0                          alsa
1                       nisulod
2                        masuya
3                       pagbuot
4                       ipanabi
5                         dakpa
6                       pukawon
7                       mogawas
8                      nadakpan
9             nadakpan, nagtupi
10                  nakalugsong
11                      mopatay
12  pagtan-aw, kitkit, paglingi
13                   pangatulig
14                        pasok
15                     magtagay
16                      molayag
17                      paabang
18                        rampa
19                       sabong
20                       taliba
21                         toyi
22                       tuslok
23                        ul-ol
24                         abot
25                        dukot
26                          agi
27                         awas
28                       bantay
29                       bukhad
30                      matulog
31                       madala
32                       makaon
33                     manguros
34                         dula
35                         duwa

In [45]:
# Shuffles the dataframe to avoid any bias when generating the sets 
df = df.sample(frac=1).reset_index(drop=True)

# Function to generate 15 rows per set (person)
def SplitExamples(df) -> list:
    example_set = []
    idx_example = 0 
    while len(example_set) < 5:
        # loop 15 times per set 
        verb_set = []
        for i in range(15):
            # Handle index out of range (36 rows)
            if idx_example > 35:
                idx_example = 0 
            verb_set.append(df.loc[idx_example].item())
            idx_example += 1
        example_set.append(pd.DataFrame({'Verbs': verb_set}))
    return example_set

first_36_df = SplitExamples(df)
for i in first_36_df:
    display(i)

          Verbs
0       nisulod
1      manguros
2      nadakpan
3       molayag
4        bukhad
5        bantay
6       pagbuot
7           agi
8         pasok
9       mopatay
10        dukot
11       makaon
12  nakalugsong
13      matulog
14       madala

                          Verbs
0                          abot
1                          dula
2                          toyi
3                       mogawas
4                          awas
5                        tuslok
6             nadakpan, nagtupi
7                       paabang
8                         rampa
9   pagtan-aw, kitkit, paglingi
10                         duwa
11                       masuya
12                        ul-ol
13                         alsa
14                       taliba

         Verbs
0     magtagay
1      ipanabi
2      pukawon
3   pangatulig
4        dakpa
5       sabong
6      nisulod
7     manguros
8     nadakpan
9      molayag
10      bukhad
11      bantay
12     pagbuot
13         agi
14       pasok

                Verbs
0             mopatay
1               dukot
2              makaon
3         nakalugsong
4             matulog
5              madala
6                abot
7                dula
8                toyi
9             mogawas
10               awas
11             tuslok
12  nadakpan, nagtupi
13            paabang
14              rampa

                          Verbs
0   pagtan-aw, kitkit, paglingi
1                          duwa
2                        masuya
3                         ul-ol
4                          alsa
5                        taliba
6                      magtagay
7                       ipanabi
8                       pukawon
9                    pangatulig
10                        dakpa
11                       sabong
12                      nisulod
13                     manguros
14                     nadakpan

## Save All Sets of Verbs
> You **MUST** change the `file_name` so you don't override the first files

In [46]:
# For convenience hehe, Change this
file_name = 'First 36 Files'

file_name = file_name.replace(' ', '_')
for idx,i in enumerate(first_36_df):
    i.to_csv(f'Dataset/Experimentation/{file_name}{idx+1}.csv',index=False)