# Splitting examples into groups
   - To be run in root

In [2]:
import pandas as pd
import numpy as np

# Miguel set of first 36 Rows
df = pd.read_csv('./Dataset/Experimentation/UniqueVerbs.csv')
df = df.loc[0:35]
df

                          Verbs
0                          alsa
1                       nisulod
2                        masuya
3                       pagbuot
4                       ipanabi
5                         dakpa
6                       pukawon
7                       mogawas
8                      nadakpan
9             nadakpan, nagtupi
10                  nakalugsong
11                      mopatay
12  pagtan-aw, kitkit, paglingi
13                   pangatulig
14                        pasok
15                     magtagay
16                      molayag
17                      paabang
18                        rampa
19                       sabong
20                       taliba
21                         toyi
22                       tuslok
23                        ul-ol
24                         abot
25                        dukot
26                          agi
27                         awas
28                       bantay
29                       bukhad
30                      matulog
31                       madala
32                       makaon
33                     manguros
34                         dula
35                         duwa

In [3]:
# Shuffles the dataframe to avoid any bias when generating the sets 
df = df.sample(frac=1).reset_index(drop=True)

# Function to generate 15 rows per set (person)
def SplitExamples(df) -> list:
    example_set = []
    idx_example = 0 
    while len(example_set) < 5:
        # loop 15 times per set 
        verb_set = []
        for i in range(15):
            # Handle index out of range (36 rows)
            if idx_example > 35:
                idx_example = 0 
            verb_set.append(df.loc[idx_example].item())
            idx_example += 1
        example_set.append(pd.DataFrame({'Verbs': verb_set}))
    return example_set

first_36_df = SplitExamples(df)
for i in first_36_df:
    display(i)

                          Verbs
0                        bantay
1                       mogawas
2                       pukawon
3                         ul-ol
4   pagtan-aw, kitkit, paglingi
5                         dakpa
6                      manguros
7                         pasok
8                       matulog
9                         rampa
10                       bukhad
11                        dukot
12            nadakpan, nagtupi
13                       makaon
14                      ipanabi

          Verbs
0          abot
1   nakalugsong
2          toyi
3          dula
4           agi
5        taliba
6       mopatay
7       nisulod
8          duwa
9        sabong
10         awas
11         alsa
12      paabang
13       tuslok
14     nadakpan

                          Verbs
0                       molayag
1                       pagbuot
2                      magtagay
3                        madala
4                    pangatulig
5                        masuya
6                        bantay
7                       mogawas
8                       pukawon
9                         ul-ol
10  pagtan-aw, kitkit, paglingi
11                        dakpa
12                     manguros
13                        pasok
14                      matulog

                Verbs
0               rampa
1              bukhad
2               dukot
3   nadakpan, nagtupi
4              makaon
5             ipanabi
6                abot
7         nakalugsong
8                toyi
9                dula
10                agi
11             taliba
12            mopatay
13            nisulod
14               duwa

         Verbs
0       sabong
1         awas
2         alsa
3      paabang
4       tuslok
5     nadakpan
6      molayag
7      pagbuot
8     magtagay
9       madala
10  pangatulig
11      masuya
12      bantay
13     mogawas
14     pukawon

## Save All Sets of Verbs
> You **MUST** change the `file_name` so you don't override the first files

In [ ]:
df['NonLiterla']

                          Verbs
0                        bantay
1                       mogawas
2                       pukawon
3                         ul-ol
4   pagtan-aw, kitkit, paglingi
5                         dakpa
6                      manguros
7                         pasok
8                       matulog
9                         rampa
10                       bukhad
11                        dukot
12            nadakpan, nagtupi
13                       makaon
14                      ipanabi
15                         abot
16                  nakalugsong
17                         toyi
18                         dula
19                          agi
20                       taliba
21                      mopatay
22                      nisulod
23                         duwa
24                       sabong
25                         awas
26                         alsa
27                      paabang
28                       tuslok
29                     nadakpan
30                      molayag
31                      pagbuot
32                     magtagay
33                       madala
34                   pangatulig
35                       masuya

### Adding Columns
Adding Literal and Non-literal columns so it's ready to be given to participants

In [27]:
sample_df = first_36_df.copy()

for i in sample_df:
    i['Literal Example'] =  pd.Series(dtype='int')
    i['Non-Literal Example'] =   pd.Series(dtype='int')
    
for i in sample_df:
    display(i)

                          Verbs  Literal Example  Non-Literal Example
0                        bantay              NaN                  NaN
1                       mogawas              NaN                  NaN
2                       pukawon              NaN                  NaN
3                         ul-ol              NaN                  NaN
4   pagtan-aw, kitkit, paglingi              NaN                  NaN
5                         dakpa              NaN                  NaN
6                      manguros              NaN                  NaN
7                         pasok              NaN                  NaN
8                       matulog              NaN                  NaN
9                         rampa              NaN                  NaN
10                       bukhad              NaN                  NaN
11                        dukot              NaN                  NaN
12            nadakpan, nagtupi              NaN                  NaN
13                       makaon              NaN                  NaN
14                      ipanabi              NaN                  NaN

          Verbs  Literal Example  Non-Literal Example
0          abot              NaN                  NaN
1   nakalugsong              NaN                  NaN
2          toyi              NaN                  NaN
3          dula              NaN                  NaN
4           agi              NaN                  NaN
5        taliba              NaN                  NaN
6       mopatay              NaN                  NaN
7       nisulod              NaN                  NaN
8          duwa              NaN                  NaN
9        sabong              NaN                  NaN
10         awas              NaN                  NaN
11         alsa              NaN                  NaN
12      paabang              NaN                  NaN
13       tuslok              NaN                  NaN
14     nadakpan              NaN                  NaN

                          Verbs  Literal Example  Non-Literal Example
0                       molayag              NaN                  NaN
1                       pagbuot              NaN                  NaN
2                      magtagay              NaN                  NaN
3                        madala              NaN                  NaN
4                    pangatulig              NaN                  NaN
5                        masuya              NaN                  NaN
6                        bantay              NaN                  NaN
7                       mogawas              NaN                  NaN
8                       pukawon              NaN                  NaN
9                         ul-ol              NaN                  NaN
10  pagtan-aw, kitkit, paglingi              NaN                  NaN
11                        dakpa              NaN                  NaN
12                     manguros              NaN                  NaN
13                        pasok              NaN                  NaN
14                      matulog              NaN                  NaN

                Verbs  Literal Example  Non-Literal Example
0               rampa              NaN                  NaN
1              bukhad              NaN                  NaN
2               dukot              NaN                  NaN
3   nadakpan, nagtupi              NaN                  NaN
4              makaon              NaN                  NaN
5             ipanabi              NaN                  NaN
6                abot              NaN                  NaN
7         nakalugsong              NaN                  NaN
8                toyi              NaN                  NaN
9                dula              NaN                  NaN
10                agi              NaN                  NaN
11             taliba              NaN                  NaN
12            mopatay              NaN                  NaN
13            nisulod              NaN                  NaN
14               duwa              NaN                  NaN

         Verbs  Literal Example  Non-Literal Example
0       sabong              NaN                  NaN
1         awas              NaN                  NaN
2         alsa              NaN                  NaN
3      paabang              NaN                  NaN
4       tuslok              NaN                  NaN
5     nadakpan              NaN                  NaN
6      molayag              NaN                  NaN
7      pagbuot              NaN                  NaN
8     magtagay              NaN                  NaN
9       madala              NaN                  NaN
10  pangatulig              NaN                  NaN
11      masuya              NaN                  NaN
12      bantay              NaN                  NaN
13     mogawas              NaN                  NaN
14     pukawon              NaN                  NaN

### Save to CSV

In [28]:
# For convenience hehe, Change this
file_name = 'First 36 Files'

file_name = file_name.replace(' ', '_')
for idx,i in enumerate(first_36_df):
    i.to_csv(f'Dataset/Experimentation/{file_name}{idx+1}.csv',index=False)