<a href="https://colab.research.google.com/github/MiguelPartosa/Thesis-FOS-BinaryClass-WSD/blob/main/Thesis_Implementation_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preload Models

In [1]:
import pandas as pd

## CEB POS Tagger -- POS Tagging

### Setup

In [2]:
!git clone https://github.com/MiguelPartosa/Thesis-FOS-BinaryClass-WSD.git
%cd Thesis-FOS-BinaryClass-WSD/Cebuano_POS_Tagger/
!pip install -r requirements.txt
import nltk
nltk.download('punkt_tab')

c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\Thesis-FOS-BinaryClass-WSD\Cebuano_POS_Tagger

Cloning into 'Thesis-FOS-BinaryClass-WSD'...
git: 'credential-gnome-keyring' is not a git command. See 'git --help'.
c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\.venv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]
ERROR: Ignored the following yanked versions: 3.1.0, 3.1.1
ERROR: Ignored the following versions that require a different python version: 3.1.1.post1 Requires-Python >=2.6, <3; 3.2.0 Requires-Python >=2.6, <3; 3.3.0 Requires-Python >=2.6, <3; 3.4.0 Requires-Python >=2.6, <3
ERROR: Could not find a version that satisfies the requirement futures==3.2.0 (from versions: 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for futures==3.2.0

Collecting backports-abc==0.5 (from -r requirements.txt (line 1))
  Using cached backports_abc-0.5-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting backports.shutil-get-terminal-size==1.0.0 (from -r requirements.txt (line 2))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting backports.shutil-which==3.5.1 (from -r requirements.txt (line 3))
  Using cached backports.shutil_which-3.5.1-py2.py3-none-any.whl.metadata (769 bytes)
Collecting bleach==2.1.3 (from -r requirements.txt (line 4))
  Using cached bleach-2.1.3-py2.py3-none-any.whl.metadata (15 kB)
Collecting colorama==0.3.9 (from -r requirements.txt (line 5))
  Using cached colorama-0.3.9-py2.py3-none-any.whl.metadata (13 kB)
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached configparser-3.5.0.tar.gz (39 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting decorator==4.3.0 (from -r requirements.txt (line 7))
  Using cached decorator-4.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting entrypoints==0.2.3 (from -r requirements.txt (line 8))
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl.metadata (382 bytes)
Collecting enum34==1.1.6 (from -r requirements.txt (line 9))
  Using cached enum34-1.1.6-py3-none-any.whl.metadata (1.7 kB)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Miguel\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### Test

In [3]:
from cebpostagger.tagger import tag_sentence

print(tag_sentence('Ang bata naligo sa sapa.'))
print(tag_sentence('Ganahan kog prutas.'))

[(b'Ang', 'DET'), (b'bata', 'NOUN'), (b'naligo', 'VERB'), (b'sa', 'PART'), (b'sapa', 'NOUN'), (b'.', 'SYM')]
[(b'Ganahan', 'VERB'), (b'kog', 'PRON'), (b'prutas', 'NOUN'), (b'.', 'SYM')]

## NLLB -- Translataion

In [4]:
from transformers import pipeline

pipe = pipeline(
    "translation", model="facebook/nllb-200-distilled-600M")

c:\Users\Miguel\Documents\Project Source Files\IT Work\School\Thesis\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
text_to_translate = "I love chicken!"

translated_text = pipe(
    text_to_translate, src_lang="eng_Latn", tgt_lang="ceb_Latn")
translated_text

[{'translation_text': 'Ganahan ko sa manok!'}]

# Dataset Preparation

## Importing Dataset

In [6]:
# @param ["Root Folder", "Cebuano_POS_Tagger"]
dataset_location = "Root Folder"
dataset_file_name = "Raw_Dataset"  # @param {type: "string"}

# For ease of use, we allow importing the dataset into the root folder
dataset_file_name = "../../" + dataset_file_name if dataset_location == "Root Folder" else dataset_file_name

df = pd.read_excel(dataset_file_name + '.xlsx', sheet_name="Cebuano_Examples")
df.head()

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o

### Tag Verbs

In [7]:
def ReturnTags(text: str) -> str:
    try:
        return tag_sentence(text)
    except Exception as e:
        print(f"{e}\n\n Input:{text}")
        return None

In [8]:
df_filtered = df.copy()
df_filtered['POS Tags'] = df_filtered.iloc[:, 0].apply(lambda x: ReturnTags(x))
df_filtered

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example,POS Tags
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o,"[(b'alsa', VERB), (b'og', CONJ), (b'balay', NO..."
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'bugoon', N..."
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o,"[(b'anak', NOUN), (b'sa', PART), (b'pobreng', ..."
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'baka', NOUN), (b'nisulod', ..."
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o,"[(b'ang', DET), (b'demalas', ADJ), (b'naa', AD..."
...,...,...,...,...,...,...,...,...,...
317,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",simile,Bisaya,(simile) cannot get along with each other,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'iring', NOUN), (b'ug', CO..."
318,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(simile, idiomatic) nouveau riche; new money; ...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'langaw', NOUN), (b'nga', ..."
319,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,used to describe someone who cries bawlingly o...,No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namatyag', VERB), (b'irin..."
320,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...",simile,Bisaya,"(simile, idiomatic) someone who leaves unexpec...",No,Wiktionary,ChatGPT 4o,"[(b'murag', ADJ), (b'namiya', OTH), (b'og', CO..."
321,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...",simile,Bisaya,"(idiomatic, simile) clear as day, clear as cry...",No,Wiktionary,ChatGPT 4o,"[(b'tin-aw', ADJ), (b'pa', ADV), (b'sa', PART)..."

#### Dataset- Export Dataset with POS Tags

- End of the first phase of preprocessing
- Unnecessary columns are dropped and columns with no meaning will be filtered out

In [9]:
# df_filtered.iloc[:,]
df_preprocessed = df_filtered[['Fos', 'Examples', 'Meaning_en', 'POS Tags']]
print("Shape before dropping NA columns: ", df_preprocessed.shape,
      "\nShape after dropping: ", df_preprocessed.dropna().shape)
# Dropping 12 columns
df_preprocessed.dropna(inplace=True)
df_preprocessed.reset_index(inplace=True, drop=True)

Shape before dropping NA columns:  (322, 4)
Shape after dropping:  (310, 4)

C:\Users\Miguel\AppData\Local\Temp\ipykernel_35356\3782929256.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_preprocessed.dropna(inplace=True)

In [10]:
df_preprocessed.to_excel(
    '../../Dataset/Tagged_POS.xlsx', sheet_name="Tagged POS", index=False)

After Manual verification, `df_filtered` is reassigned to the manually verified dataset with the proper tags

## Dataset Verb Verification

### Verification

- Process after the dataset is manually tagged as verbs or not verbs

---

**New Columns After Verification:**

- Machine Tagged Verb
  - An excel formula to identify if the tagger tagged any verbs
- Accurate Verb Tags
  - Our own verification if the tagger accurately or innacurately tagged verbs
- Contains Verbs
  - Our own input if the FOS contains verbs
- Needs Correction
  - An excel formula to guide corrections
- Corrected - Contains Verbs
  - Corrected values by our Linguist

> [!WARNING]  
> "Accurate Verb Tags" will be removed as its unnecessary

In [11]:
#  TODO temporary dataset treated as final
# Importing cleaned dataset
df_verified = pd.read_excel("../../Dataset/TEMP_POS Tags Verification.xlsx")
df_verified

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",(often humorous) used to call someone dumb or ...,"[(b'anak', 'NOUN'), (b'sa', 'PART'), (b'bugoon...",0,1,0,No,NaN
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",a mere mortal; an ordinary person; someone wit...,"[(b'anak', 'NOUN'), (b'sa', 'PART'), (b'pobren...",0,1,0,No,NaN
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",used to dismiss people's opinion on one's luck...,"[(b'ang', 'DET'), (b'demalas', 'ADJ'), (b'naa'...",0,0,0,No,NaN
...,...,...,...,...,...,...,...,...,...
305,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",(simile) cannot get along with each other,"[(b'murag', 'ADJ'), (b'iring', 'NOUN'), (b'ug'...",0,1,0,No,NaN
306,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...","(simile, idiomatic) nouveau riche; new money; ...","[(b'murag', 'ADJ'), (b'langaw', 'NOUN'), (b'ng...",1,1,1,No,NaN
307,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",used to describe someone who cries bawlingly o...,"[(b'murag', 'ADJ'), (b'namatyag', 'VERB'), (b'...",1,1,1,No,NaN
308,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...","(simile, idiomatic) someone who leaves unexpec...","[(b'murag', 'ADJ'), (b'namiya', 'OTH'), (b'og'...",0,0,1,Yes,NaN
309,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...","(idiomatic, simile) clear as day, clear as cry...","[(b'tin-aw', 'ADJ'), (b'pa', 'ADV'), (b'sa', '...",0,0,0,No,NaN

### Filtering Non-Verbs

- Verification must be done before filtering out tagged verbs

In [12]:
# TODO: After verification, change Contains verbs to Corrected column
df_verbs_filtered = df_verified[df_verified['Contains Verbs'] == 1].reset_index(
    drop=True)
df_verbs_filtered

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",used to tell someone not to criticize or hate ...,"[(b'ang', 'DET'), (b'masuya', 'VERB'), (b'made...",1,1,1,No,NaN
3,ayaw pagbuot kay lain-lain ta og lubot,"Ayaw pagbuot kay lain-lain ta og lubot, respet...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b'k...",1,0,1,No,NaN
4,"ayaw pagbuot, lain-lain tag lubot","Ayaw pagbuot, lain-lain tag lubot, tanan kita ...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b',...",1,0,1,No,NaN
...,...,...,...,...,...,...,...,...,...
151,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...","(idiomatic, simile) someone who leaves their d...","[(b'mura', 'ADJ'), (b'og', 'CONJ'), (b'halas',...",1,1,1,No,NaN
152,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",(simile) spotless; spick-and-span,"[(b'murag', 'ADJ'), (b'gitilapan', 'VERB'), (b...",1,1,1,No,NaN
153,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...","(simile, idiomatic) nouveau riche; new money; ...","[(b'murag', 'ADJ'), (b'langaw', 'NOUN'), (b'ng...",1,1,1,No,NaN
154,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",used to describe someone who cries bawlingly o...,"[(b'murag', 'ADJ'), (b'namatyag', 'VERB'), (b'...",1,1,1,No,NaN
155,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...","(simile, idiomatic) someone who leaves unexpec...","[(b'murag', 'ADJ'), (b'namiya', 'OTH'), (b'og'...",0,0,1,Yes,NaN

## Word Sense

### Word Sense Cleaning

Removing tpye of FOS inside parenthesis

In [13]:
df_verbs_filtered

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",used to tell someone not to criticize or hate ...,"[(b'ang', 'DET'), (b'masuya', 'VERB'), (b'made...",1,1,1,No,NaN
3,ayaw pagbuot kay lain-lain ta og lubot,"Ayaw pagbuot kay lain-lain ta og lubot, respet...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b'k...",1,0,1,No,NaN
4,"ayaw pagbuot, lain-lain tag lubot","Ayaw pagbuot, lain-lain tag lubot, tanan kita ...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b',...",1,0,1,No,NaN
...,...,...,...,...,...,...,...,...,...
151,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...","(idiomatic, simile) someone who leaves their d...","[(b'mura', 'ADJ'), (b'og', 'CONJ'), (b'halas',...",1,1,1,No,NaN
152,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",(simile) spotless; spick-and-span,"[(b'murag', 'ADJ'), (b'gitilapan', 'VERB'), (b...",1,1,1,No,NaN
153,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...","(simile, idiomatic) nouveau riche; new money; ...","[(b'murag', 'ADJ'), (b'langaw', 'NOUN'), (b'ng...",1,1,1,No,NaN
154,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",used to describe someone who cries bawlingly o...,"[(b'murag', 'ADJ'), (b'namatyag', 'VERB'), (b'...",1,1,1,No,NaN
155,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...","(simile, idiomatic) someone who leaves unexpec...","[(b'murag', 'ADJ'), (b'namiya', 'OTH'), (b'og'...",0,0,1,Yes,NaN

In [14]:
import re

# Example
sample_set = df_verbs_filtered.iloc[151:156, [2]]


def CleanWordSense(meaning: str) -> str:
    # Strip characters inside parenthesis inclusively
    clean = re.sub(r'\s*\([^)]*\)', '', meaning).strip()

    # Set of delimiters observed in the column
    delimiters = [';', '.', ',']

    pattern = f"[{''.join(re.escape(char) for char in delimiters)}]"

    # Find the first occurrence in clean
    match = re.search(pattern, clean)

    return clean[0:match.start()] if match else clean


sample_set['Meaning_en'].apply(CleanWordSense)

151    someone who leaves their dirty clothes everywh...
152                                             spotless
153                                        nouveau riche
154    used to describe someone who cries bawlingly o...
155      someone who leaves unexpectedly without sa word
Name: Meaning_en, dtype: object

In [15]:
df_cleaned_sense = df_verbs_filtered.copy()
df_cleaned_sense['Cleaned Word Sense'] = df_cleaned_sense.iloc[:, 2].apply(
    CleanWordSense)
df_cleaned_sense['Cleaned Word Sense']

0      said to self or someone when the meal includes...
1      used to tell someone that he is a liar or you ...
2      used to tell someone not to criticize or hate ...
3                               don't tell me what to do
4                               don't tell me what to do
                             ...
151    someone who leaves their dirty clothes everywh...
152                                             spotless
153                                        nouveau riche
154    used to describe someone who cries bawlingly o...
155      someone who leaves unexpectedly without sa word
Name: Cleaned Word Sense, Length: 156, dtype: object

In [16]:
df_cleaned_sense.to_excel(
    '../../Dataset/Cleaned_Word_sense.xlsx', sheet_name="Cleaned Word Sense", index=False)

### Translate English Wordsense into Cebuano

In [17]:
example = df_cleaned_sense.iloc[151:153].reset_index(drop=True)
example

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs,Cleaned Word Sense
0,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...","(idiomatic, simile) someone who leaves their d...","[(b'mura', 'ADJ'), (b'og', 'CONJ'), (b'halas',...",1,1,1,No,NaN,someone who leaves their dirty clothes everywh...
1,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",(simile) spotless; spick-and-span,"[(b'murag', 'ADJ'), (b'gitilapan', 'VERB'), (b...",1,1,1,No,NaN,spotless

Translator example from nllb

In [18]:
def TranslateCebuano(text: str) -> str:
    try:
        translated_text = pipe(text, src_lang="eng_Latn", tgt_lang="ceb_Latn")
        return translated_text[0]['translation_text']
    except Exception as e:
        print(f"{e}\n\n Input:{text}")
        return ""

In [19]:
print("Original Example: ", example['Cleaned Word Sense'][0], "\n\nTranslated:", TranslateCebuano(
    example['Cleaned Word Sense'][0]))

Original Example:  someone who leaves their dirty clothes everywhere around the house

Translated: ang usa ka tawo nga magbiya sa iyang mahugaw nga sinina sa tanang dapit sa balay

In [20]:
df_translated = df_cleaned_sense.copy()
df_translated["Translated Word Sense"] = df_cleaned_sense['Cleaned Word Sense'].apply(
    lambda x: TranslateCebuano(x))
df_translated

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs,Cleaned Word Sense,Translated Word Sense
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN,said to self or someone when the meal includes...,gisulti sa kaugalingon o sa uban kon ang pagka...
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN,used to tell someone that he is a liar or you ...,gigamit sa pagsulti sa usa nga siya usa ka bak...
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",used to tell someone not to criticize or hate ...,"[(b'ang', 'DET'), (b'masuya', 'VERB'), (b'made...",1,1,1,No,NaN,used to tell someone not to criticize or hate ...,gigamit sa pagsulti sa usa nga dili magkritika...
3,ayaw pagbuot kay lain-lain ta og lubot,"Ayaw pagbuot kay lain-lain ta og lubot, respet...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b'k...",1,0,1,No,NaN,don't tell me what to do,ayaw ako isulti kon unsay buhaton
4,"ayaw pagbuot, lain-lain tag lubot","Ayaw pagbuot, lain-lain tag lubot, tanan kita ...",don't tell me what to do,"[(b'ayaw', 'VERB'), (b'pagbuot', 'NOUN'), (b',...",1,0,1,No,NaN,don't tell me what to do,ayaw ako isulti kon unsay buhaton
...,...,...,...,...,...,...,...,...,...,...,...
151,mura og halas nga nagluno,"""Ang iyang mga sinina nagkatag mura og halas n...","(idiomatic, simile) someone who leaves their d...","[(b'mura', 'ADJ'), (b'og', 'CONJ'), (b'halas',...",1,1,1,No,NaN,someone who leaves their dirty clothes everywh...,ang usa ka tawo nga magbiya sa iyang mahugaw n...
152,murag gitilapan og iring,"""Ang iyang sapatos murag gitilapan og iring, l...",(simile) spotless; spick-and-span,"[(b'murag', 'ADJ'), (b'gitilapan', 'VERB'), (b...",1,1,1,No,NaN,spotless,walay sapayan
153,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...","(simile, idiomatic) nouveau riche; new money; ...","[(b'murag', 'ADJ'), (b'langaw', 'NOUN'), (b'ng...",1,1,1,No,NaN,nouveau riche,nouveau riche
154,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",used to describe someone who cries bawlingly o...,"[(b'murag', 'ADJ'), (b'namatyag', 'VERB'), (b'...",1,1,1,No,NaN,used to describe someone who cries bawlingly o...,gigamit sa paghulagway sa usa ka tawo nga nagt...
155,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...","(simile, idiomatic) someone who leaves unexpec...","[(b'murag', 'ADJ'), (b'namiya', 'OTH'), (b'og'...",0,0,1,Yes,NaN,someone who leaves unexpectedly without sa word,Usa ka tawo nga mibiya sa dili-iasa nga walay ...

Saving the dataframe checkpoint since the translation process takes up a lot of time

In [21]:
df_translated.to_excel(
    '../../Dataset/Translated_Word_sense.xlsx', sheet_name="Translated", index=False)

In [22]:
# Re-reading the dataframe with translations
df_translated = pd.read_excel('../../Dataset/Translated_Word_sense.xlsx')

# Dataset Transformation

The following columns will be generated before the train and test split:

- (1) FOS/expression
- (2) their literal usage
- (3) their non-literal usage

Get the verb out of the given row

In [23]:
import ast
# For converting the converted list strings into lists

In [24]:
def ExtractVerbs(tags: str | tuple) -> list:
    return [x[0].decode("utf-8") for x in ast.literal_eval(tags) if x[1] == 'VERB']

In [25]:
df_translated['Verbs'] = df_translated['POS Tags'].apply(ExtractVerbs)
df_translated.head(3)

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs,Cleaned Word Sense,Translated Word Sense,Verbs
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN,said to self or someone when the meal includes...,gisulti sa kaugalingon o sa uban kon ang pagka...,[alsa]
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN,used to tell someone that he is a liar or you ...,gigamit sa pagsulti sa usa nga siya usa ka bak...,[nisulod]
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",used to tell someone not to criticize or hate ...,"[(b'ang', 'DET'), (b'masuya', 'VERB'), (b'made...",1,1,1,No,NaN,used to tell someone not to criticize or hate ...,gigamit sa pagsulti sa usa nga dili magkritika...,[masuya]

In [26]:
df_translated['Figure of Speech'] = 1
df_translated.head(3)

,Fos,Examples,Meaning_en,POS Tags,Machine Tagged Verb,Accurate Verb Tags,Contains Verbs,Needs Correction,Corrected - Contains Verbs,Cleaned Word Sense,Translated Word Sense,Verbs,Figure of Speech
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,said to self or someone when the meal includes...,"[(b'alsa', 'VERB'), (b'og', 'CONJ'), (b'balay'...",1,1,1,No,NaN,said to self or someone when the meal includes...,gisulti sa kaugalingon o sa uban kon ang pagka...,[alsa],1
1,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",used to tell someone that he is a liar or you ...,"[(b'ang', 'DET'), (b'baka', 'NOUN'), (b'nisulo...",1,1,1,No,NaN,used to tell someone that he is a liar or you ...,gigamit sa pagsulti sa usa nga siya usa ka bak...,[nisulod],1
2,ang masuya madeads,"Si Maria kay permi nalang masuya, maong ang ma...",used to tell someone not to criticize or hate ...,"[(b'ang', 'DET'), (b'masuya', 'VERB'), (b'made...",1,1,1,No,NaN,used to tell someone not to criticize or hate ...,gigamit sa pagsulti sa usa nga dili magkritika...,[masuya],1

> [!WARNING]  
> Column names will be replaced once data transformation is finalized and some features will be dropped for clarity

Final columns might look like this (have to discuss with group)

- FOS
- Example (their literal or nonliteral use)
- Literal Word Sense
- Nonliteral Word Sense
- Verb

Additionally, for the test set

- Is FOS (The actual label of the FOS in use)

In [27]:
# TO remove, df_dataset is created as soon as the first operations fo data transformation is done on previous dataframe
df_dataset = pd.DataFrame(
    {'FOS': df_translated['Fos'],
     'Word Sense': df_translated['Translated Word Sense'],
     'Non-literal Usage': df_translated['Examples'],
     'Literal Usage': df_translated['Examples'],
     'Verb': df_translated['Verbs'],
     'Is FOS': df_translated['Figure of Speech']
     })
df_dataset.head(3)

,FOS,Word Sense,Non-literal Usage,Literal Usage,Verb,Is FOS
0,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,Siya'y alsa og balay kada buntag aron makataba...,Siya'y alsa og balay kada buntag aron makataba...,[alsa],1
1,ang baka nisulod sa kulon,gigamit sa pagsulti sa usa nga siya usa ka bak...,"Sa dihang nagluto siya, naay baka nisulod sa k...","Sa dihang nagluto siya, naay baka nisulod sa k...",[nisulod],1
2,ang masuya madeads,gigamit sa pagsulti sa usa nga dili magkritika...,"Si Maria kay permi nalang masuya, maong ang ma...","Si Maria kay permi nalang masuya, maong ang ma...",[masuya],1

In [28]:
df_dataset.to_excel("../../Dataset/Template_Unexpanded.xlsx", index=False)

In [29]:
df_dataset = pd.read_excel("../../Dataset/Template_Unexpanded.xlsx")

# Combining Augmented Dataset

In [30]:
df_augmented = pd.read_excel('../../Dataset/Augmented_Dataset.xlsx')
df_augmented.head(3)

,FOS/Expression,Meaning,Non-Literal Usage,Literal Usage,Similarity Score
0,alsa og balay,said to self or someone when the meal includes...,Siya'y alsa og balay kada buntag aron makataba...,Nag-alsa sila og balay ngadto sa pikas baranga...,NaN
1,alsa og balay,said to self or someone when the meal includes...,Ang mga bata sa bukid kay alsa og balay para m...,Gihangyo sa pamilya ang ilang mga silingan nga...,NaN
2,alsa og balay,said to self or someone when the meal includes...,"Sa dihang naglisod sila, alsa og balay ang tan...",Nag-alsa og balay ang pamilya kay mobalhin sil...,NaN

In [31]:
df_merged_final = pd.merge(
    left=df_dataset, right=df_augmented, left_on='FOS', right_on='FOS/Expression')
df_merged_final = df_merged_final.drop(columns=['Meaning', 'Non-literal Usage', 'Is FOS', 'FOS/Expression',
                                       'Literal Usage_x', 'Similarity Score']).rename(columns={"Literal Usage_y": "Literal Usage"})
display(df_merged_final.head(3),
        df_merged_final.shape)

,FOS,Word Sense,Verb,Non-Literal Usage,Literal Usage
0,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Siya'y alsa og balay kada buntag aron makataba...,Nag-alsa sila og balay ngadto sa pikas baranga...
1,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Ang mga bata sa bukid kay alsa og balay para m...,Gihangyo sa pamilya ang ilang mga silingan nga...
2,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],"Sa dihang naglisod sila, alsa og balay ang tan...",Nag-alsa og balay ang pamilya kay mobalhin sil...

(805, 5)

In [32]:
df_merged_final.to_excel(
    "../../Dataset/Final_Dataset_NoLabels.xlsx", index=False)

# Train and Test Split

The train and test split will be done at random and two main datasets will be created. One dataset is for Cbert, which has a label and another dataset is for the ensemble model. Both will have a train and test split.

In [33]:
from sklearn.model_selection import train_test_split

### Train Test Split with NO Labels

In [34]:
df_train, df_test = train_test_split(df_merged_final, test_size=0.2)
display(df_test.head(3), df_test.shape, df_train.head(3), df_train.shape)

,FOS,Word Sense,Verb,Non-Literal Usage,Literal Usage
246,anak sa sala,usa ka anak nga dili-konsejero,['sala'],Ang anak sa sala nga si Maria kay ginaatiman g...,Ang anak sa sala nagdula duol sa altar samtang...
144,gibuhi,ang penis sa usa ka lalaki,['gibuhi'],Ang mga bata nga iyang gibuhi kay nagdako nga ...,Si Lola ang gibuhi sa among gidala nga gamay n...
80,nadakpan na ba ang nagtupi nimo,gisultihan sa usa ka tawo nga adunay bag-ong b...,['nagtupi'],Nadakpan na ba ang nagtupi nimo nga wala man n...,Gidala dayon siya sa istasyon sa pulis ug giin...

(161, 5)

,FOS,Word Sense,Verb,Non-Literal Usage,Literal Usage
606,magpalapad og papel,aron magbaton ug dungog sa buhat sa uban,['magpalapad'],Ang iyang kauban sa trabaho pirmi magpalapad o...,Nagpalit siya og balayronon sa papel sa tindah...
803,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"""Ang silingan murag namiya og tai, kalit lang ...",Ang bata nagdali sa pagdagan kay murag namiya ...
646,makawat,mahimong ma-stolen,['makawat'],"Si Pedro makawat kaayo, dali ra siya madala bi...",Ang bata nakit-an nga makawat og mga mansanas ...

(644, 5)

In [35]:
df_test.to_excel('../../Dataset/Test_Set.xlsx', index=False)
df_train.to_excel('../../Dataset/Train_Set.xlsx', index=False)

### Train Test Split with Labels

In [36]:
def SplitUsage(df_input:pd.DataFrame)-> pd.DataFrame:  
    df_split = pd.DataFrame()
    for x in df_input.iterrows():
        split_df = pd.DataFrame({
                'FOS': [x[1]['FOS'] for _ in range(2)],
                'Word Sense': [x[1]['Word Sense'] for _ in range(2)],
                'Verb': [x[1]['Verb'] for _ in range(2)],
                'Usage': [x[1]['Non-Literal Usage'], x[1]['Literal Usage']],
                'Is FOS' : [1,0]
                })
        
        df_split = pd.concat([df_split, split_df])
    return df_split.reset_index(drop=True)
    
SplitUsage(df_merged_final).head(3)

,FOS,Word Sense,Verb,Usage,Is FOS
0,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Siya'y alsa og balay kada buntag aron makataba...,1
1,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Nag-alsa sila og balay ngadto sa pikas baranga...,0
2,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Ang mga bata sa bukid kay alsa og balay para m...,1

In [37]:
df_merged_final_labels = SplitUsage(df_merged_final)
df_merged_final_labels

,FOS,Word Sense,Verb,Usage,Is FOS
0,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Siya'y alsa og balay kada buntag aron makataba...,1
1,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Nag-alsa sila og balay ngadto sa pikas baranga...,0
2,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Ang mga bata sa bukid kay alsa og balay para m...,1
3,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],Gihangyo sa pamilya ang ilang mga silingan nga...,0
4,alsa og balay,gisulti sa kaugalingon o sa uban kon ang pagka...,['alsa'],"Sa dihang naglisod sila, alsa og balay ang tan...",1
...,...,...,...,...,...
1605,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"Pagkahuman kaon sa iyang pamahaw, si Jun-jun m...",0
1606,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"""Ang silingan murag namiya og tai, kalit lang ...",1
1607,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],Ang bata nagdali sa pagdagan kay murag namiya ...,0
1608,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"""Si Ana murag namiya og tai, wala na gani nagp...",1
1609,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"""Nakita nako si Tomas nga nagdali-dali padung ...",0

In [38]:
df_merged_final_labels.to_excel(
    "../../Dataset/Final_Dataset_WithLabels.xlsx", index=False)

In [39]:
df_merged_final_labels = pd.read_excel("../../Dataset/Final_Dataset_WithLabels.xlsx")

In [40]:
display(SplitUsage(df_test).head(3), SplitUsage(df_test).shape, SplitUsage(df_train).head(3), SplitUsage(df_train).shape)

,FOS,Word Sense,Verb,Usage,Is FOS
0,anak sa sala,usa ka anak nga dili-konsejero,['sala'],Ang anak sa sala nga si Maria kay ginaatiman g...,1
1,anak sa sala,usa ka anak nga dili-konsejero,['sala'],Ang anak sa sala nagdula duol sa altar samtang...,0
2,gibuhi,ang penis sa usa ka lalaki,['gibuhi'],Ang mga bata nga iyang gibuhi kay nagdako nga ...,1

(322, 5)

,FOS,Word Sense,Verb,Usage,Is FOS
0,magpalapad og papel,aron magbaton ug dungog sa buhat sa uban,['magpalapad'],Ang iyang kauban sa trabaho pirmi magpalapad o...,1
1,magpalapad og papel,aron magbaton ug dungog sa buhat sa uban,['magpalapad'],Nagpalit siya og balayronon sa papel sa tindah...,0
2,murag namiya og tai,Usa ka tawo nga mibiya sa dili-iasa nga walay ...,[],"""Ang silingan murag namiya og tai, kalit lang ...",1

(1288, 5)

In [41]:
SplitUsage(df_test).to_excel('../../Dataset/Test_Set_WLabels.xlsx', index=False)
SplitUsage(df_train).to_excel('../../Dataset/Train_Set_WLabels.xlsx', index=False)