<a href="https://colab.research.google.com/github/MiguelPartosa/Thesis-FOS-BinaryClass-WSD/blob/main/Thesis_Implementation_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preload Models

## CEB POS Tagger -- POS Tagging

### Setup

In [ ]:
!git clone https://github.com/MiguelPartosa/Thesis-FOS-BinaryClass-WSD.git
%cd Thesis-FOS-BinaryClass-WSD/
%cd Cebuano_POS_Tagger/
!pip install -r requirements.txt
import nltk
nltk.download('punkt_tab')

Cloning into 'Thesis-FOS-BinaryClass-WSD'...
remote: Enumerating objects: 133, done.
remote: Counting objects: 100% (133/133), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 133 (delta 39), reused 117 (delta 25), pack-reused 0 (from 0)
Receiving objects: 100% (133/133), 16.49 MiB | 18.25 MiB/s, done.
Resolving deltas: 100% (39/39), done.
/content/Thesis-FOS-BinaryClass-WSD/Cebuano_POS_Tagger/Thesis-FOS-BinaryClass-WSD
/content/Thesis-FOS-BinaryClass-WSD/Cebuano_POS_Tagger/Thesis-FOS-BinaryClass-WSD/Cebuano_POS_Tagger
Collecting backports-abc==0.5 (from -r requirements.txt (line 1))
  Using cached backports_abc-0.5-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting backports.shutil-get-terminal-size==1.0.0 (from -r requirements.txt (line 2))
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting backports.shutil-which==3.5.1 (from -r requirements.txt (line 3))
  Using cached backports.shutil_which-3.5.1-py2.py3-none-any.whl.metadata (769 bytes)
Collecting bleach==2.1.3 (from -r requirements.txt (line 4))
  Using cached bleach-2.1.3-py2.py3-none-any.whl.metadata (15 kB)
Collecting colorama==0.3.9 (from -r requirements.txt (line 5))
  Using cached colorama-0.3.9-py2.py3-none-any.whl.metadata (13 kB)
Collecting configparser==3.5.0 (from -r requirements.txt (line 6))
  Using cached configparser-3.5.0.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Collecting decorator==4.3.0 (from -r requirements.txt (line 7))
  Using cached decorator-4.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting entrypoints==0.2.3 (from -r requirements.txt (line 8))
  Using cached entrypoints-0.2.3-py2.py3-none-any.whl.metadata (382 bytes)
Collecting enum34==1.1.6 (from -r requirements.txt (line 9))
  Using cached enum34-1.1.6-py3-none-any.whl.metadata (1.7 kB)
ERROR: Ignored the following yanked versions: 3.1.0, 3.1.1
ERROR: Ignored the following versions that require a different python version: 3.1.1.post1 Requires-Python >=2.6, <3; 3.2.0 Requires-Python >=2.6, <3; 3.3.0 Requires-Python >=2.6, <3; 3.4.0 Requires-Python >=2.6, <3
ERROR: Could not find a version that satisfies the requirement futures==3.2.0 (from versions: 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5)
ERROR: No matching distribution found for futures==3.2.0

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

### Test

In [ ]:
from cebpostagger.tagger import tag_sentence

print(tag_sentence('Ang bata naligo sa sapa.'))
print(tag_sentence('Ganahan kog prutas.'))

[(b'Ang', 'DET'), (b'bata', 'NOUN'), (b'naligo', 'VERB'), (b'sa', 'PART'), (b'sapa', 'NOUN'), (b'.', 'SYM')]
[(b'Ganahan', 'VERB'), (b'kog', 'PRON'), (b'prutas', 'NOUN'), (b'.', 'SYM')]

## NLLB -- Translataion

In [29]:
from transformers import pipeline

pipe = pipeline("translation", model="facebook/nllb-200-distilled-600M")

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

Device set to use cpu

In [30]:
text_to_translate = "I love chicken!"

translated_text = pipe(text_to_translate, src_lang="eng_Latn", tgt_lang="ceb_Latn")
translated_text

[{'translation_text': 'Ganahan ko sa manok!'}]

## Sentence Transformer -- Sentence Embeddings

In [138]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('sentence-transformers/LaBSE')

modules.json:   0%|          | 0.00/461 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/2.22k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/804 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.88G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/397 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/5.22M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.62M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.36M [00:00<?, ?B/s]

2_Dense/config.json:   0%|          | 0.00/114 [00:00<?, ?B/s]

# Dataset Preparation

## Importing Dataset

In [131]:
import pandas as pd

df = pd.read_excel("MASTER_FILE.xlsx", sheet_name ="Cebuano_Examples")
df.head()

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,a mere mortal; an ordinary person; someone wit...,No,Wiktionary,ChatGPT 4o
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,used to tell someone that he is a liar or you ...,No,Wiktionary,ChatGPT 4o
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,used to dismiss people's opinion on one's luck...,No,Wiktionary,ChatGPT 4o

### Translate English Wordsense into Cebuano

In [87]:
!pip install tqdm
from tqdm import tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)

In [132]:
example = df.iloc[:2]
example

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,said to self or someone when the meal includes...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(often humorous) used to call someone dumb or ...,No,Wiktionary,ChatGPT 4o

Translator example from nllb

In [136]:
def TranslateCebuano(text:str) -> str:
  try:
    translated_text = pipe(text, src_lang="eng_Latn", tgt_lang="ceb_Latn")
    return translated_text[0]['translation_text']
  except Exception as e:
    print(f"{e}\n\n Input:{text}")
    return ""

In [69]:
print("Original Example: ",example.iloc[:,4][0],"\n\nTranslated:",TranslateCebuano(example.iloc[:,4][0]))

Original Example:  said to self or someone when the meal includes mung beans

Translated: gisulti sa kaugalingon o sa uban kon ang pagkaon naglakip sa mung beans

In [137]:
df_translated = df.copy()
df_translated.iloc[:,4] = df_translated.iloc[:,4].apply(lambda x: TranslateCebuano(x))
df_translated

Your input_length: 819 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 234 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
Your input_length: 453 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)
Token indices sequence length is longer than the specified maximum sequence length for this model (1554 > 1024). Running this sequence through the model will result in indexing errors
Your input_length: 1554 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 314 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).

 Input:nan

Your input_length: 377 is bigger than 0.9 * max_length: 200. You might consider increasing your max_length manually, e.g. translator('...', max_length=400)

,Fos,Examples,Fos_category,Native_lang,Meaning_en,Medical_context,Source_fos,Source_example
0,alsa og balay,Siya'y alsa og balay kada buntag aron makataba...,catchphrases,Bisaya,gisulti sa kaugalingon o uban kon ang pagkaon ...,No,Wiktionary,ChatGPT 4o
1,anak sa bugoon,"Si Pedro kay anak sa bugoon, bisan unsa'y trab...",catchphrases,Bisaya,(masulob-on nga mapahitas-on) gigamit sa pagta...,No,Wiktionary,ChatGPT 4o
2,anak sa pobreng utin,"Si Juan kay anak sa pobreng utin, pero nagkugi...",catchphrases,Bisaya,usa ka mortal lamang; usa ka ordinaryo nga taw...,No,Wiktionary,ChatGPT 4o
3,ang baka nisulod sa kulon,"Sa dihang nagluto siya, naay baka nisulod sa k...",catchphrases,Bisaya,gigamit sa pagsulti sa usa nga siya usa ka bak...,No,Wiktionary,ChatGPT 4o
4,ang demalas naa sa menteryo,"Bisan unsaon niya paglikay, ang demalas naa sa...",catchphrases,Bisaya,gigamit sa paglabay sa opinyon sa mga tawo bah...,No,Wiktionary,ChatGPT 4o
...,...,...,...,...,...,...,...,...
317,murag iring ug iro,"""Si Juan ug Pedro murag iring ug iro, sige lan...",simile,Bisaya,(simile) dili makab-ot sa usag usa,No,Wiktionary,ChatGPT 4o
318,murag langaw nga nakatugdon sa kabaw,"""Siya karon murag langaw nga nakatugdon sa kab...",simile,Bisaya,"(similar, idiomatic) nouveau rich; bag-ong sal...",No,Wiktionary,ChatGPT 4o
319,murag namatyag iring,"""Si Pedro murag namatyag iring, sige lang hila...",simile,Bisaya,gigamit sa paghulagway sa usa ka tawo nga nagt...,No,Wiktionary,ChatGPT 4o
320,murag namiya og tai,"""Siya kalit lang murag namiya og tai, wala na ...",simile,Bisaya,"(same, idiomatic) usa ka tawo nga mibiya sa di...",No,Wiktionary,ChatGPT 4o
321,tin-aw pa sa sabaw sa butong,"""Ang iyang pangutana tin-aw pa sa sabaw sa but...",simile,Bisaya,"(idiomatic, simile) limpyo sama sa adlaw, limp...",No,Wiktionary,ChatGPT 4o

# Dataset Transformation

## TODO for 50%
  - [ ] Import dataset with pandas
  - [ ] Run CEBPOS tags on column 2 and filter
  - [ ] Transform per row example in column 28 into multiple rows
  - [ ] Use gpt to generate literal examples and find literal example from seperate dataset
  - [ ] Show innacurate/hallucinated generated from gpt examples and remove from rows

## Maybe included ?
  - [ ] Train Test split